[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "memory"
format = " $icon_swap $swap_used_percents.eng(w:2) "




[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime() "

[[block]]
block = "maildir"
interval = 60
inboxes = ["~/Mail/ai-automatica/INBOX/", "~/Mail/gmail/INBOX/", "~/Mail/ireen/INBOX/", "~/Mail/ur/INBOX/", "~/Mail/wu/INBOX/"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
